apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      tolerations:
        - key: "application"
          operator: "Equal"
          value: {{ .Values.appName }}
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: application
                    operator: In
                    values:
                      - {{ .Values.appName }}
      containers:
        - name: {{ .Values.appName }}-container
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.connectivity.containerPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.connectivity.containerPort }}
          ports:
            - containerPort: {{ .Values.connectivity.containerPort }}